/**
 * Glossary of RAG terminology for inline educational tooltips.
 * Used by GlossaryTooltip throughout the UI.
 */

export const GLOSSARY: Record<string, string> = {
  "cosine similarity":
    "A score (0–1) measuring the angle between two embedding vectors. 1 = identical meaning, 0 = unrelated. Used by vector retrieval to rank chunks.",

  bm25: "A keyword ranking algorithm based on term frequency and document length. No embeddings required — fast, interpretable, and strong on exact-match queries.",

  "BM25": "A keyword ranking algorithm based on term frequency and document length. No embeddings required — fast, interpretable, and strong on exact-match queries.",

  "vector search":
    "Retrieval based on embedding similarity. The query is embedded and compared to stored chunk embeddings using cosine distance. Good at semantic matching even when words differ.",

  "hybrid search":
    "Combines vector and BM25 rankings using Reciprocal Rank Fusion. Gets the benefits of both semantic and keyword matching.",

  "reciprocal rank fusion":
    "A fusion method that combines rankings from multiple retrievers. Score = Σ 1/(k + rank_i). Works without needing comparable scores across retrievers.",

  rrf: "Reciprocal Rank Fusion — combines rankings from multiple retrievers. Score = Σ 1/(k + rank_i). Works without needing comparable scores across retrievers.",

  "RRF": "Reciprocal Rank Fusion — combines rankings from multiple retrievers. Score = Σ 1/(k + rank_i). Works without needing comparable scores across retrievers.",

  "top-k":
    "The number of chunks returned by retrieval. Higher k = more context for the LLM, but also more noise. Tune this to balance recall vs precision.",

  "chunking strategy":
    "How a document is split into pieces before embedding. Chunk size and overlap affect what fits in a single retrieved result and whether important context is split across boundaries.",

  embedding:
    "A fixed-length vector of numbers representing the semantic meaning of a piece of text. Similar texts have similar vectors. Generated by Voyage AI (voyage-3) in this platform.",

  faithfulness:
    "Does the generated answer only contain information present in the retrieved chunks? Scored 1–5 by Claude Haiku, then normalised to 0–1. High faithfulness = low hallucination.",

  relevance:
    "Are the retrieved chunks — and the generated answer — actually relevant to the question? Scored 1–5 by Claude Haiku, then normalised to 0–1.",

  recall:
    "Was the chunk used to generate the ground-truth answer present in the top-k retrieved set? Binary: 1.0 (found) or 0.0 (missed). Measures retrieval coverage, not answer quality.",

  "llm-as-judge":
    "Using a language model (Claude Haiku) to score answer quality on a numeric scale, instead of exact-match string metrics. Enables nuanced evaluation of open-ended answers.",

  "LLM-as-judge":
    "Using a language model (Claude Haiku) to score answer quality on a numeric scale, instead of exact-match string metrics. Enables nuanced evaluation of open-ended answers.",

  "chunk overlap":
    "The number of characters shared between adjacent chunks. Overlap ensures that sentences split at a chunk boundary still appear in context in at least one chunk.",
};
